In [40]:
https://chat.openai.com/share/8c5506ba-8ac4-4886-994b-69d0580baf29

SyntaxError: invalid decimal literal (<ipython-input-40-724ed8e8fcd6>, line 1)

In [10]:
pip install scikit-learn

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score, train_test_split

In [12]:
model = LinearRegression()
print(model)

LinearRegression()


In [36]:
import numpy as np
from sklearn.model_selection import train_test_split

In [18]:
X , y = np.arange(10).reshape((5, 2)), range(5)

In [19]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
list(y)

[0, 1, 2, 3, 4]

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3)

In [31]:
X_train

array([[8, 9],
       [4, 5],
       [2, 3]])

In [29]:
y_train

[4, 0, 1]

In [32]:
X_test

array([[6, 7],
       [0, 1]])

In [33]:
y_test

[3, 0]

In [37]:
model.fit(X_train, y_train)

LinearRegression()

In [38]:
predictions = model.predict(X_test)

In [39]:
predictions

array([3., 0.])