** A collection of modules that are linked together is also known as p Pyhton library. It has code bundles that can be used agin and agin in differnet programs. For programmers, it makes Python programming easier and simpler. Since then, we will not need to compose the same code for varius projects **

In [2]:
import numpy as np

In [7]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [3]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
print('%d bytes' %(v.size * v.itemsize))

80 bytes


In [11]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
v = np.arange(10, 20)
print(v)

[10 11 12 13 14 15 16 17 18 19]


In [14]:
import numpy as np
v = np.arange(10, 50)
print(v)
print(type(v))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
<class 'numpy.ndarray'>


In [17]:
v = np.arange(50)
print(v)
v = v[::-1]
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**1. The range function is a built-in
  Python function that returns an immutable sequence of numbers within a specified range. It is commonly used in for loops to iterate over a sequence of numbers.
2. The arange function is not a built-in
  Python function but rather a function provided by the NumPy library, which is widely used for numerical computations. NumPy is especially popular for working with arrays and matrices efficiently.

**

In [20]:
v = np.arange(9).reshape(3 ,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
nz = np.nonzero([1,0,0,2,0,0,3,0,0,0,4,0,0,0,0,0,5,0,0,0,0,0,6])
print(nz)

(array([ 0,  3,  6, 10, 16, 22]),)


In [22]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
v = np.eye(5)
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
v = np.random.random(10)
print(v)

[0.47684048 0.19730568 0.59316304 0.26636    0.67688243 0.40587996
 0.91920877 0.16169717 0.40607729 0.14808356]


In [30]:
v = np.random.random((10 ,10))
print(v)

[[0.44479958 0.6969674  0.34311493 0.52900738 0.51926521 0.41416485
  0.77291288 0.64622656 0.17498225 0.02465576]
 [0.78209735 0.77603116 0.35446113 0.30945159 0.49693798 0.42825847
  0.40416543 0.3689155  0.26972994 0.84434055]
 [0.2932934  0.00929344 0.7250855  0.33858696 0.90145033 0.75616693
  0.77334157 0.75438702 0.67655217 0.05456118]
 [0.577589   0.26002802 0.37712521 0.75889089 0.80928903 0.59092061
  0.36875359 0.82952784 0.66844011 0.07735718]
 [0.43898713 0.31323638 0.20771662 0.50192227 0.98700811 0.18092874
  0.47767386 0.20889111 0.1501767  0.88225515]
 [0.41566173 0.11899481 0.9267688  0.82492813 0.52710685 0.1257325
  0.15377693 0.78545574 0.61806474 0.62252352]
 [0.51827843 0.88950057 0.17706538 0.79856637 0.86941001 0.02686792
  0.34754162 0.93989144 0.39104788 0.85627269]
 [0.81874669 0.26141822 0.19100152 0.68137838 0.04273564 0.86127681
  0.31885269 0.55888199 0.49925226 0.28867338]
 [0.34006011 0.16260721 0.55408337 0.44901193 0.96273711 0.64739508
  0.64935767 

In [32]:
v = np.random.random((3 ,3, 3))
print(v)

[[[0.73290828 0.43661823 0.88996808]
  [0.95805331 0.79531256 0.16287957]
  [0.53057928 0.85018797 0.57011694]]

 [[0.7919702  0.74364548 0.62005969]
  [0.48167945 0.034949   0.1959683 ]
  [0.62263341 0.19217076 0.31398534]]

 [[0.70206404 0.78844787 0.48018092]
  [0.68552127 0.85026709 0.1836464 ]
  [0.8104431  0.17744328 0.08936702]]]


In [34]:
v = np.random.random((2,2,2))
print(v)

[[[0.22353902 0.58221563]
  [0.41727485 0.75666002]]

 [[0.25274973 0.46674073]
  [0.3656913  0.0888699 ]]]


In [40]:
v = np.random.random((2,2))
x = np.round(v ,2)*100
print(x)

[[86.  5.]
 [98. 88.]]


In [42]:
v = np.random.random((3,3,3))
x = np.round(v ,2)*100
print(x)

[[[1000.  450.  800.]
  [ 600.  620.  800.]
  [  20.  970.  700.]]

 [[ 270.  320.  420.]
  [ 370.  390.  430.]
  [ 230.  330.  710.]]

 [[ 560.  260.   10.]
  [ 730.  380.  630.]
  [ 930.  750.  860.]]]


In [47]:
vy = np.random.random(5)
print("Random array:", vy)


p = np.random.random((3, 3))
print("Random matrix:", p)


Random array: [0.76545093 0.94010507 0.806445   0.09133735 0.82825164]
Random matrix: [[0.86928337 0.1709164  0.25710054]
 [0.43985092 0.89943327 0.16789297]
 [0.38879546 0.62185332 0.36687001]]


In [52]:
v = np.random.random((10, 10))
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

0.9929434237737897 0.012442763555681524


In [58]:
v = np.random.random(10)
v_sum = v.sum()
v_mean = v.mean()
print(v_sum)
print(v_mean)

4.455146066247365
0.4455146066247365


In [59]:
v = np.ones((10, 10))
print(v)
v[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [62]:
v = np.zeros((10, 10))
# print(v)
v[1:-1, 1:-1] = 1
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [67]:
v = np.zeros((10, 10))
# print(v)
v[1:len(v)-1, 1:len(v)-1] = 1
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [74]:

v = np.ones((5,5))
# print(v)

v = np.pad(v, pad_width=1, mode='constant', constant_values=0)
print(v)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [75]:
np.nan

nan

In [76]:
print(np.nan + 5)
v = np.ones((10,np.nan))
v[1:np.nan, 1:-1] = 0
print(v)

nan
False
False
nan
False


In [77]:
print(0.3)
print(3*0.1)

0.3
0.30000000000000004


In [86]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

z = np.diag(1 + np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
