In [ ]:
import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np

In [ ]:
df = pd.read_excel('/content/Data (1).xlsx')

In [ ]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
x = df.iloc[:, :3]
y = df.iloc[:, -1]

In [ ]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
imputer = SimpleImputer(missing_values = np.nan, strategy= 'mean')
columns_to_impute = ['Age', 'Salary']
df[columns_to_impute] = imputer.fit_transform(df[columns_to_impute]).round(0)
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  39.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

#Encoding Catagorical data

In [ ]:
from matplotlib import transforms
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
x

array([[0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 4.0e+01,     nan],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00,     nan, 5.2e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])

#Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

#Splitting the dataset into the Training set and Test set#

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
x_train, x_test, y_train, y_test

(array([[1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 4.0e+01,     nan],
        [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04],
        [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
        [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00,     nan, 5.2e+04],
        [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04],
        [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
        [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
        [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04]]),
 array([[1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
        [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]]),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

Feature Selection

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

x_train[:, 3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.fit_transform(x_test[:,3:])
x_train, x_test

(array([[ 1.        ,  0.        ,  1.        , -0.77459667,  0.25315802,
                 nan],
        [ 0.        ,  1.        ,  0.        , -0.77459667, -0.23014365,
          0.44897083],
        [ 1.        ,  0.        ,  0.        ,  1.29099445, -1.84114924,
         -1.41706417],
        [ 1.        ,  0.        ,  0.        ,  1.29099445,         nan,
         -1.0242147 ],
        [ 0.        ,  1.        ,  0.        , -0.77459667,  1.54196248,
          1.62751925],
        [ 1.        ,  0.        ,  0.        ,  1.29099445, -0.0690431 ,
         -0.14030338],
        [ 0.        ,  1.        ,  0.        , -0.77459667,  0.89756025,
          0.94003267],
        [ 0.        ,  1.        ,  0.        , -0.77459667, -0.55234477,
         -0.43494049]]),
 array([[ 1.,  0.,  1.,  0., -1., -1.],
        [ 1.,  0.,  1.,  0.,  1.,  1.]]))