In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df = pd.read_csv('/content/AB_NYC_2019.csv')

In [5]:
df.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [6]:
df.groupby("host_id")["reviews_per_month"].nunique()

host_id
2438         1
2571         1
2787         6
2845         2
2868         1
            ..
274273284    0
274298453    0
274307600    0
274311461    0
274321313    0
Name: reviews_per_month, Length: 37457, dtype: int64

In [7]:
def custom_agg(series):
    num_reviews_gt_zero = series[series > 0]
    if num_reviews_gt_zero.empty:
        return 0
    else:
        return num_reviews_gt_zero.mean()


result = df.groupby("host_id")["reviews_per_month"].agg(custom_agg)

result = result.fillna(0)

In [8]:
df.head(3)

id                                 name  host_id  host_name  \
0  2539   Clean & quiet apt home by the park     2787       John   
1  2595                Skylit Midtown Castle     2845   Jennifer   
2  3647  THE VILLAGE OF HARLEM....NEW YORK !     4632  Elisabeth   

  neighbourhood_group neighbourhood  latitude  longitude        room_type  \
0            Brooklyn    Kensington  40.64749  -73.97237     Private room   
1           Manhattan       Midtown  40.75362  -73.98377  Entire home/apt   
2           Manhattan        Harlem  40.80902  -73.94190     Private room   

   price  minimum_nights  number_of_reviews last_review  reviews_per_month  \
0    149               1                  9  2018-10-19               0.21   
1    225               1                 45  2019-05-21               0.38   
2    150               3                  0         NaN                NaN   

   calculated_host_listings_count  availability_365  
0                               6               365  
1                               2               355  
2                               1               365

In [9]:
neighbourhood_group = pd.get_dummies(df['neighbourhood_group'], drop_first = True)
neighbourhood_group.head()

Brooklyn  Manhattan  Queens  Staten Island
0         1          0       0              0
1         0          1       0              0
2         0          1       0              0
3         1          0       0              0
4         0          1       0              0

In [10]:
room_type_group = pd.get_dummies(df['room_type'], drop_first = True)
room_type_group.head()

Private room  Shared room
0             1            0
1             0            0
2             1            0
3             0            0
4             0            0

In [11]:
df = pd.concat([df, neighbourhood_group, room_type_group], axis = 1)
df.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  ...  last_review  reviews_per_month  \
0     Private room    149  ...   2018-10-19               0.21   
1  Entire home/apt    225  ...   2019-05-21               0.38   
2     Private room    150  ...          NaN                NaN   
3  Entire home/apt     89  ...   2019-07-05               4.64   
4  Entire home/apt     80  ...   2018-11-19               0.10   

  calculated_host_listings_count  availability_365  Brooklyn  Manhattan  \
0                              6               365         1          0   
1                              2               355         0          1   
2                              1               365         0          1   
3                              1               194         1          0   
4                              1                 0         0          1   

   Queens  Staten Island  Private room  Shared room  
0       0              0             1            0  
1       0              0             0            0  
2       0              0             1            0  
3       0              0             0            0  
4       0              0             0            0  

[5 rows x 22 columns]

In [12]:
df['reviews_per_month'].fillna(0, inplace=True)
df.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                     0
calculated_host_listings_count        0
availability_365                      0
Brooklyn                              0
Manhattan                             0
Queens                                0
Staten Island                         0
Private room                          0
Shared room                           0
dtype: int64

In [13]:
df.drop(['id', 'host_id','neighbourhood_group','name','host_name', 'availability_365','neighbourhood','room_type','last_review'], axis=1, inplace=True)
df.head()

latitude  longitude  price  minimum_nights  number_of_reviews  \
0  40.64749  -73.97237    149               1                  9   
1  40.75362  -73.98377    225               1                 45   
2  40.80902  -73.94190    150               3                  0   
3  40.68514  -73.95976     89               1                270   
4  40.79851  -73.94399     80              10                  9   

   reviews_per_month  calculated_host_listings_count  Brooklyn  Manhattan  \
0               0.21                               6         1          0   
1               0.38                               2         0          1   
2               0.00                               1         0          1   
3               4.64                               1         1          0   
4               0.10                               1         0          1   

   Queens  Staten Island  Private room  Shared room  
0       0              0             1            0  
1       0              0             0            0  
2       0              0             1            0  
3       0              0             0            0  
4       0              0             0            0

In [14]:
X = df.drop('price', axis=1)

y = df['price']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=101)

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
dtree = DecisionTreeClassifier()

In [19]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [20]:
predictions = dtree.predict(X_test)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix

In [22]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
          10       0.00      0.00      0.00         3
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         0
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         8
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          25       0.11      0.25      0.15        12
          26       0.08      0.17      0.11         6
          27       0.00      0.00      0.00         3
          28       0.11      0.12      0.12         8
          29       0.11      0.08      0.09        13
          30       0.19    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [23]:
print(confusion_matrix(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

In [ ]:
rfc_pred = rfc.predict(X_test)