In [ ]:
import numpy as np

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [ ]:
lst_one = [11, 22, 33, 44, 55, 66, 77, 88, 99, 110]
array = np.array(lst_one)
print(type(array))

<class 'numpy.ndarray'>


In [ ]:
tup_one = (12, 23, 34, 45, 56, 67, 78, 89, 90)
arr = np.array(tup_one)
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
dict_one  ={'a':[1,2,3,4,5,0],'b':(True,False),'c':'Python','d':'Programming'}
arr4 = np.array(dict_one)
arr4

array({'a': [1, 2, 3, 4, 5, 0], 'b': (True, False), 'c': 'Python', 'd': 'Programming'},
      dtype=object)

In [12]:
set1 = {1,2,3,4,5,0,True,False,'Python','Programming'}
arr3 = np.array(set1)
arr3

array({0, 1, 2, 3, 4, 5, 'Programming', 'Python'}, dtype=object)

In [13]:
str1 = 'Python Programming'
arr5 = np.array(str1)
print(arr5)

Python Programming


In [15]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
arr.ndim

[ 1  2  3  4  5  6  7  8  9 10]


1

In [19]:
arr_2d = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(arr_2d)
arr_2d.ndim

[[1 2 3 4 5]
 [9 8 7 6 5]]


2

In [23]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)
arr_3d.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [27]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([
    [[[1, 2], [4, 5]], [[1, 2], [4, 5]]],
    [[[11, 12], [14, 15]], [[11, 12], [14, 15]]]
    ])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4
