In [120]:
my_list = [1,2,3]

In [121]:
my_list

[1, 2, 3]

In [122]:
import numpy as np

In [123]:
np.array(my_list)

array([1, 2, 3])

In [124]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [125]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [126]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [129]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [131]:
np.zeros(3)

array([0., 0., 0.])

In [132]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [133]:
np.ones(3)

array([1., 1., 1.])

In [134]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [135]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [136]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [137]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [138]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [139]:
np.random.rand(5)

array([0.96210884, 0.34240475, 0.91552551, 0.8217068 , 0.97785424])

In [140]:
np.random.rand(5,5)

array([[0.15195482, 0.53294399, 0.46905071, 0.50633925, 0.67235324],
       [0.1054061 , 0.25292798, 0.75675693, 0.58358813, 0.48581359],
       [0.28454152, 0.3242069 , 0.93165271, 0.93117327, 0.42288326],
       [0.20357489, 0.48727821, 0.25747316, 0.82093923, 0.69635424],
       [0.39616604, 0.16947242, 0.21572827, 0.26377742, 0.55243499]])

In [141]:
np.random.randn(25)

array([ 1.3325861 ,  0.20768479, -1.14141549,  0.4473757 ,  1.63263271,
       -0.63481586,  0.05407697, -1.63454317,  0.57640178,  1.22942298,
       -1.3922773 , -0.34987399,  0.82880127,  0.47186484, -0.67457008,
        1.0243926 ,  0.74647606,  0.70921287,  1.04411283, -2.51999821,
        0.08649372,  2.12026354,  0.77982457,  0.74758485, -1.51929443])

In [142]:
np.random.randn(4,4)

array([[-0.05200862,  1.10989463,  0.36904707, -0.08155428],
       [-2.01022679, -0.0719018 ,  0.47728723,  0.34880273],
       [ 0.1210824 , -0.04914745, -0.47414793, -1.05238552],
       [ 0.26758967,  0.03320249, -0.4226086 ,  0.12258859]])

In [143]:
np.random.randint(1, 100)

22

In [144]:
np.random.randint(1, 100, 10)

array([91, 61, 86, 63, 11, 11, 92,  2, 82, 96])

In [145]:
arr = np.arange(25)

In [146]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [147]:
ranarr = np.random.randint(0, 50,10)

In [148]:
ranarr.max()

47

In [149]:
ranarr.min()

15

In [150]:
ranarr.argmax()

5

In [151]:
arr = arr.reshape(5,5)

In [152]:
arr.shape

(5, 5)

In [153]:
arr.dtype

dtype('int32')

In [154]:
from numpy.random import randint, randn

In [155]:
randint(2, 10)

4

In [156]:
randn(2,5)

array([[-0.80051133, -0.40394308,  0.9938657 , -1.17716049,  0.6454417 ],
       [-0.26755089,  1.038826  , -0.58519856,  0.91883179, -1.28883893]])

In [157]:
arr = np.arange(0,11)

In [158]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:
arr[2]

2

In [160]:
arr[2:6]

array([2, 3, 4, 5])

In [161]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [162]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [163]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [164]:
arr[0:5] = 100

In [165]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [168]:
ar = np.arange(0,11)

In [169]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
slice_of_arr = arr[0:6]

In [171]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [172]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [173]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [174]:
arr_2d[0]

array([ 5, 10, 15])

In [175]:
arr_2d[1][1]

25

In [176]:
arr_2d[2][1]

40

In [177]:
arr_2d[1,2]

30

In [178]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [182]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [183]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [184]:
arr = np.arange(1,11)

In [185]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [187]:
bool_arr = arr > 5

In [188]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [189]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [190]:
arr[arr < 5]

array([1, 2, 3, 4])

In [192]:
arr_22d = np.arange(50).reshape(5,10)

In [193]:
arr_22d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [197]:
arr_22d[1:3,2:4]

array([[12, 13],
       [22, 23]])

In [198]:
import numpy as np

In [200]:
arr = np.arange(0,11)

In [201]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [202]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [203]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [204]:
arr / arr 

C:\Users\DELL\AppData\Local\Temp\ipykernel_11248\2663351161.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [205]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [206]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [207]:
arr.max()

10

In [208]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [210]:
np.log(arr)

C:\Users\DELL\AppData\Local\Temp\ipykernel_11248\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [211]:
import numpy as np

In [212]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [214]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [215]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [216]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [217]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [220]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [225]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [237]:
from numpy.random import randn, rand

In [246]:
rand(1)

array([0.65802643])

In [248]:
rand(2)

array([0.58408009, 0.67345283])

In [239]:
randn(25)

array([ 0.73906209, -0.27604226,  1.493545  ,  0.65843011,  1.14256154,
       -0.39402808,  0.72552453,  0.14591284,  0.67727877,  0.17383012,
       -0.16687274,  1.47608372,  0.96466735,  1.1389054 , -0.05976091,
       -1.63121858, -1.40652444, -0.2139599 ,  0.1617259 , -0.52838579,
       -0.98073572,  0.35980404,  0.55000814, -0.09856779, -0.74670683])

In [257]:
np.linspace(0,1,100).reshape(10,10)

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [260]:
result = np.arange(1,101)/100

In [261]:
result.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [262]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [265]:
np.linspace(1,101,100).reshape(10,10)/100

array([[0.01      , 0.02010101, 0.03020202, 0.04030303, 0.05040404,
        0.06050505, 0.07060606, 0.08070707, 0.09080808, 0.10090909],
       [0.1110101 , 0.12111111, 0.13121212, 0.14131313, 0.15141414,
        0.16151515, 0.17161616, 0.18171717, 0.19181818, 0.20191919],
       [0.2120202 , 0.22212121, 0.23222222, 0.24232323, 0.25242424,
        0.26252525, 0.27262626, 0.28272727, 0.29282828, 0.30292929],
       [0.3130303 , 0.32313131, 0.33323232, 0.34333333, 0.35343434,
        0.36353535, 0.37363636, 0.38373737, 0.39383838, 0.40393939],
       [0.4140404 , 0.42414141, 0.43424242, 0.44434343, 0.45444444,
        0.46454545, 0.47464646, 0.48474747, 0.49484848, 0.50494949],
       [0.51505051, 0.52515152, 0.53525253, 0.54535354, 0.55545455,
        0.56555556, 0.57565657, 0.58575758, 0.59585859, 0.6059596 ],
       [0.61606061, 0.62616162, 0.63626263, 0.64636364, 0.65646465,
        0.66656566, 0.67666667, 0.68676768, 0.69686869, 0.7069697 ],
       [0.71707071, 0.72717172, 0.7372727

In [266]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [268]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [270]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [271]:
mat[3,4]

20

In [272]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [275]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [276]:
mat[4]

array([21, 22, 23, 24, 25])

In [277]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [278]:
mat[3]

array([16, 17, 18, 19, 20])

In [279]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [280]:
np.sum(mat)

325

In [281]:
np.std(mat)

7.211102550927978

In [291]:
for i in range(5):
    np.sum(mat[:,i])
    

In [292]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [293]:
np.sum(mat, axis=1)

array([ 15,  40,  65,  90, 115])